name: tag and github release
on:
  workflow_call:
    inputs:
      prerelease:
        type: boolean
        required: false
        default: false
        description: use a prerelease instead of a regular release
      githubToken:
        type: string
        required: false
        default: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
        description: github token used for repo interactions

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: inputs.githubToken

      - uses: salesforcecli/github-workflows/.github/actions/getPreReleaseTag@main
        id: distTag
        if: inputs.prerelease

      - name: prerelease package.json validation
        if: inputs.prerelease && !steps.distTag.outputs.tag
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Prerelease requires a dist tag name in your package.json like beta in 1.1.1-beta.0')

      - name: Conventional Changelog Action
        id: changelog
        uses: salesforcecli/conventional-changelog-action@prereleases
        with:
          git-user-name: svc-cli-bot
          git-user-email: svc_cli_bot@salesforce.com
          github-token: inputs.githubToken
          output-file: "false"
          tag-prefix: ""
      - name: Create Github Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: inputs.githubToken
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: ${{ inputs.prerelease }}
