on:
  workflow_call:

jobs:
  tarballs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: salesforcecli/cli
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
      - run: |
          yarn add ${{ github.repository }}#${{ github.sha }} --network-concurrency 1
          yarn pack:tarballs -t linux-x64 --no-xz
          yarn pack:verify
