on:
  workflow_call:
    inputs:
      command:
        required: false
        type: string
        default: yarn test:nuts
        description: "command to execute (ex: yarn test:nuts)"
      nodeVersion:
        required: false
        description: version of node to run tests against.  Use things like [lts/-1, lts/*, latest] to avoid hardcoding versions
        type: string
        default: lts/*
      os:
        required: false
        description: "runs-on property, ex: ubuntu-latest, windows-latest"
        type: string
        default: "ubuntu-latest"
      sfdxExecutablePath:
        required: false
        description: "Path to sfdx executable to be used by NUTs, defaults to ''"
        type: string
      useCache:
        required: false
        type: boolean
        default: true
      retries:
        required: false
        type: number
        default: 3
        description: "Number of times to retry NUTs [max 5]"

jobs:
  nut:
    env:
      TESTKIT_AUTH_URL: ${{ secrets.TESTKIT_AUTH_URL}}
      TESTKIT_HUB_USERNAME: ${{ secrets.TESTKIT_HUB_USERNAME }}
      TESTKIT_JWT_CLIENT_ID: ${{ secrets.TESTKIT_JWT_CLIENT_ID }}
      TESTKIT_JWT_KEY: ${{ secrets.TESTKIT_JWT_KEY }}
      TESTKIT_HUB_INSTANCE: ${{ secrets.TESTKIT_HUB_INSTANCE }}
      ONEGP_TESTKIT_AUTH_URL: ${{ secrets.ONEGP_TESTKIT_AUTH_URL }}
      TESTKIT_SETUP_RETRIES: 2
    name: ${{ inputs.command }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: google/wireit@setup-github-actions-caching/v1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: yarn
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn config set network-timeout 600000
      - run: yarn global add sfdx-cli@latest-rc @salesforce/cli@latest-rc
      - run: yarn install
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}
      - run: yarn compile
      - run: echo "TESTKIT_EXECUTABLE_PATH=${{inputs.sfdxExecutablePath}}" >> $GITHUB_ENV
        if: inputs.sfdxExecutablePath
      - name: NUTs attempt 1
        id: nut1
        continue-on-error: inputs.retries > 1
        run: ${{ inputs.command }}

      - name: NUTs attempt 2
        id: nut2
        continue-on-error: true
        if: steps.nut1.outcome == 'failure' && inputs.retries >= 2
        run: ${{ inputs.command }}

      - name: NUTs attempt 3
        id: nut3
        continue-on-error: true
        if: steps.nut2.outcome == 'failure' && inputs.retries >= 3
        run: ${{ inputs.command }}

      - name: NUTs attempt 4
        id: nut4
        continue-on-error: true
        if: steps.nut3.outcome == 'failure' && inputs.retries >= 4
        run: ${{ inputs.command }}

      - name: NUTs attempt 5
        if: steps.nut4.outcome == 'failure' && inputs.retries == 5
        run: ${{ inputs.command }}
