on:
  workflow_call:
    inputs:
      cli:
        type: string
        required: true
        description: only needed if upload. sfdx or sf
      version:
        type: string
        required: true
        description: version for upload. do not include the 'v'
      channel:
        type: string
        required: true
        description: channel that the uploaded tarballs get promoted to

jobs:
  macos:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SFDX_HIDE_RELEASE_NOTES: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
        name: yarn install
        with:
          max_attempts: 5
          command: yarn install --network-timeout 600000
          timeout_minutes: 10
      # todo: download the macos tarball and pass that to the oclif pack:macos command
      - run: yarn pack:macos
      - run: yarn upload:macos
      - run: yarn channel:promote --cli ${{ inputs.cli }} --version ${{ inputs.version }} --target ${{ inputs.channel }} --platform macos
        name: Promote macos to ${{ inputs.channel }} channel
