on:
  workflow_call:

jobs:
  windows-unit-tests:
    strategy:
      matrix:
        node_version: [lts/*, latest]
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google/wireit@setup-github-actions-caching/v1
        continue-on-error: true
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}
      - run: yarn build
      - name: yarn test
        uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
        with:
          max_attempts: 2
          command: yarn test
          timeout_minutes: 60
        env:
          SF_DISABLE_TELEMETRY: true
