on:
  workflow_call:

jobs:
  windows-unit-tests:
    strategy:
      matrix:
        # node_version: [lts/-1, lts/*, latest]
        node_version: [lts/-1, lts/*]
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google/wireit@setup-github-actions-caching/v1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}
        name: yarn install
        with:
          max_attempts: 5
          command: yarn install --network-timeout 600000
          timeout_minutes: 10
      - run: yarn build
      - run: yarn test
